# Generated by Django 4.2.11 on 2024-03-28 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('assessment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('result_details', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
