# Generated by Django 5.0.3 on 2024-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_assessmenthistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Response",
        ),
        migrations.AddField(
            model_name="assessmenthistory",
            name="max_score",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
