# Generated by Django 4.1.13 on 2024-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_delete_chat_delete_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthistory',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
