# Generated by Django 4.1.13 on 2024-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_assessmenthistory_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthistory',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
