# Generated by Django 4.1.13 on 2024-04-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0005_alter_assessmenthistory_date_taken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
