# Generated by Django 4.1.13 on 2024-04-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_question_subject_assesstype_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
