# Generated by Django 4.1.13 on 2024-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0008_assessmenthistory_subject_assessmenthistory_topic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="subjects",
            fields=[
                (
                    "assessment_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("subject", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="assessmenthistory",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="assessmenthistory",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="assessmenthistory",
            name="type",
        ),
    ]
