# Generated by Django 4.1.13 on 2024-04-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_subject_assesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthistory',
            name='assess_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chatbot.assesstype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='subjects',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='chatbot.subject'),
            preserve_default=False,
        ),
    ]
