# Generated by Django 4.1.13 on 2024-04-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_sub_assess'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenthistory',
            name='assess_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chatbot.assess'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmenthistory',
            name='subjects',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chatbot.sub'),
            preserve_default=False,
        ),
    ]
