# Generated by Django 4.1.13 on 2024-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_assessmenthistory_assess_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assessmenthistory',
            name='assess_type',
        ),
        migrations.RemoveField(
            model_name='assessmenthistory',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='AssessType',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
