# Generated by Django 4.1.13 on 2024-04-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0010_delete_subjects_assessmenthistory_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
            ],
        ),
    ]
