# Generated by Django 4.1.13 on 2024-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0011_assessmentsubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
            ],
        ),
    ]
