# Generated by Django 4.1.13 on 2024-04-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_remove_assessmenthistory_assess_type_and_more'),
        ('chatbot', '0013_assessmentformat'),
    ]

    operations = [
    ]
