# Generated by Django 4.1.13 on 2024-05-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0018_alter_answer_question_alter_answer_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenthistory",
            name="recommendation_message",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
