# Generated by Django 4.1.13 on 2024-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0020_document_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_questions", models.IntegerField()),
                ("subject", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
    ]
