# Generated by Django 5.0.6 on 2024-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0024_alter_questionbank_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="assessment_id",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
